# Scoreboard Options

currentEvent: "None"
host: "None"
length: 0   # Must be in milliseconds!!
toggled: true

# Chat Option
chat:
  toggled: false

# Event Options
waterRising:
  toggled: false

bossbar:
    toggled: false
    title: "None"