name: SootEvents
version: '${project.version}'
main: net.sootmc.sootevents.SootEvents
api-version: 1.19
authors: [ JamieIsGeek ]
description: A base plugin for SootMC's events!

commands:
    scoreboard:
        description: Command to interact with the events scoreboard
        usage: /scoreboard <on|off|start|pause|reload>
        permission: sootevents.command.scoreboard

    togglechat:
        description: Command to toggle the chat
        usage: /togglechat
        permission: sootevents.command.togglechat

    toggledamager:
        description: Command to toggle the damager on contact with water
        usage: /toggledamager
        permission: sootevents.command.toggledamager

    bossbar:
        description: Command to toggle the bossbar
        usage: /bossbar <on|off|reload>
        permission: sootevents.command.togglebossbar

permissions:
    sootevents.command.eventscore:
        description: Allows the user to use the /scoreboard command
        default: op

    sootevents.command.togglechat:
        description: Allows the user to use the /togglechat command
        default: op

    sootevents.command.toggledamager:
        description: Allows the user to use the /toggledamager command
        default: op

    sootevents.command.bossbar:
        description: Allows the user to use the /bossbar command
        default: op